swagger: "2.0"
info:
  description: "This is an anime info api server."
  version: "1.0.0"
  title: "Swagger AnimeInfo"
  termsOfService: "http://swagger.io/terms/"
basePath: "/api"
tags:
- name: "anime"
  description: "Anime Info"
schemes:
- "http"
paths:
  /anime_lists/{year}/{cour}:
    get:
      tags:
      - "anime"
      summary: "Get Anime Info"
      description: ""
      operationId: "GetAnimelists"
      produces:
      - "application/json"
      parameters:
      - name: "year"
        in: "path"
        description: "Broadcast year"
        required: true
        type: "string"
      - name: "cour"
        in: "path"
        description: "Broadcast cour"
        required: true
        type: "integer"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AnimeList"
        400:
          description: "Missing Parameters"
        404:
          description: "Not Found"
  /anime_site_previews:
    post:
      tags:
      - "anime"
      summary: "Get Anime Site Preview"
      description: ""
      operationId: "GetAnimeSitePreview"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          schema:
            type: object
            properties:
              link_url:
                type: "string"
                description: "anime site link url"
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              previewImageUrl:
                type: "string"
                description: "site preview image url"
        400:
          description: "Missing Parameters"
        404:
          description: "Not Found"
definitions:
  AnimeList:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      link:
        type: "string"